#Add required language & version below, this is just an example
language: generic
python:
  - "3.7"
  - "3.6"
install:
    - pip install pylama
    - pip install pylint
script:
  - python3 --version
  - python3 travis-tests/test1.py
  - pylama
